#!/usr/bin/env bash

# Date: lundi 9 février 2015, 23:42:58 (UTC+0100)
# Generated by:
# sh run-generator.sh egfr104 'erbb1 erbb2 erbb3 erbb4 ar bir btc egf epr hbegf nrg1a nrg1b nrg2a nrg2b nrg3 nrg4 tgfa sos1r eps8r csrc pi3kr pten ship2 pdk1 pp2a mtorr mkp pp2b' 'elk1 creb ap1 hsp27 actin_reorg cmyc pro_apoptotic p70s6_2 pkc stat1 stat3 stat5'

# File: egfr104.ph
# Inputs: erbb1 erbb2 erbb3 erbb4 ar bir btc egf epr hbegf nrg1a nrg1b nrg2a nrg2b nrg3 nrg4 tgfa sos1r eps8r csrc pi3kr pten ship2 pdk1 pp2a mtorr mkp pp2b
# Outputs: elk1 creb ap1 hsp27 actin_reorg cmyc pro_apoptotic p70s6_2 pkc stat1 stat3 stat5

ph="egfr104.ph"
outputs="elk1 creb ap1 hsp27 actin_reorg cmyc pro_apoptotic p70s6_2 pkc stat1 stat3 stat5"
mode=${1}

echo -n "Start time: " && date
echo 'Model: egfr104.ph'
echo 'Inputs: erbb1 erbb2 erbb3 erbb4 ar bir btc egf epr hbegf nrg1a nrg1b nrg2a nrg2b nrg3 nrg4 tgfa sos1r eps8r csrc pi3kr pten ship2 pdk1 pp2a mtorr mkp pp2b'
echo 'Outputs: elk1 creb ap1 hsp27 actin_reorg cmyc pro_apoptotic p70s6_2 pkc stat1 stat3 stat5'

(echo -n "Start time: " && date) >&2
(echo 'Model: egfr104.ph') >&2
(echo 'Inputs: erbb1 erbb2 erbb3 erbb4 ar bir btc egf epr hbegf nrg1a nrg1b nrg2a nrg2b nrg3 nrg4 tgfa sos1r eps8r csrc pi3kr pten ship2 pdk1 pp2a mtorr mkp pp2b') >&2
(echo 'Outputs: elk1 creb ap1 hsp27 actin_reorg cmyc pro_apoptotic p70s6_2 pkc stat1 stat3 stat5') >&2

for erbb1 in 0 1; do
for erbb2 in 0 1; do
for erbb3 in 0 1; do
for erbb4 in 0 1; do
for ar in 0 1; do
for bir in 0 1; do
for btc in 0 1; do
for egf in 0 1; do
for epr in 0 1; do
for hbegf in 0 1; do
for nrg1a in 0 1; do
for nrg1b in 0 1; do
for nrg2a in 0 1; do
for nrg2b in 0 1; do
for nrg3 in 0 1; do
for nrg4 in 0 1; do
for tgfa in 0 1; do
for sos1r in 0 1; do
for eps8r in 0 1; do
for csrc in 0 1; do
for pi3kr in 0 1; do
for pten in 0 1; do
for ship2 in 0 1; do
for pdk1 in 0 1; do
for pp2a in 0 1; do
for mtorr in 0 1; do
for mkp in 0 1; do
for pp2b in 0 1; do

init="erbb1 $erbb1, erbb2 $erbb2, erbb3 $erbb3, erbb4 $erbb4, ar $ar, bir $bir, btc $btc, egf $egf, epr $epr, hbegf $hbegf, nrg1a $nrg1a, nrg1b $nrg1b, nrg2a $nrg2a, nrg2b $nrg2b, nrg3 $nrg3, nrg4 $nrg4, tgfa $tgfa, sos1r $sos1r, eps8r $eps8r, csrc $csrc, pi3kr $pi3kr, pten $pten, ship2 $ship2, pdk1 $pdk1, pp2a $pp2a, mtorr $mtorr, mkp $mkp, pp2b $pp2b"
echo "--- $init"
for z in $outputs; do
  echo "# $z 1"
  ./unitrun.sh $mode "x" --no-debug --initial-state "$init" -i $ph $z 1
  [ $? -eq 137 ] && echo '*** Killed ***'
done

done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done
done

echo -n "End time: " && date
(echo -n "End time: " && date) >&2

