#!/usr/bin/env bash



# Comments:
# This script tests all outputs when a given input is active,
# in the predefined configuration:
#   erbb1 = 1 & erbb2 = 0 & erbb4 = 1
# The following inputs seem to have an influence:
#   erbb3 = 1 \/
#   bir = 1 \/ btc = 1 \/ egf = 1 \/ epr = 1 \/
#   nrg1a = 1 \/ nrg1b = 1 \/ nrg2b = 1 \/ nrg4 = 1 \/ tgfa 1
# The activation of the following outputs is then compromised:
#   elk1, creb, ap1, actin_reorg, cmyc



# Date: lundi 9 février 2015, 20:06:05 (UTC+0100)
# Generated by:
# sh run-generator.sh egfr104 'erbb1 erbb2 erbb3 erbb4 ar bir btc egf epr hbegf nrg1a nrg1b nrg2a nrg2b nrg3 nrg4 tgfa' 'elk1 creb ap1 hsp27 actin_reorg cmyc pro_apoptotic p70s6_2 pkc stat1 stat3 stat5'

# File: egfr104.ph
# Inputs: erbb1 erbb2 erbb3 erbb4 ar bir btc egf epr hbegf nrg1a nrg1b nrg2a nrg2b nrg3 nrg4 tgfa
# Outputs: elk1 creb ap1 hsp27 actin_reorg cmyc pro_apoptotic p70s6_2 pkc stat1 stat3 stat5

ph="egfr104.ph"
outputs="elk1 creb ap1 hsp27 actin_reorg cmyc pro_apoptotic p70s6_2 pkc stat1 stat3 stat5"
mode=${1}

echo -n "Start time: " && date
echo 'Model: egfr104.ph'
echo 'Outputs: elk1 creb ap1 hsp27 actin_reorg cmyc pro_apoptotic p70s6_2 pkc stat1 stat3 stat5'

for curinput in erbb3 ar bir btc egf epr hbegf nrg1a nrg1b nrg2a nrg2b nrg3 nrg4 tgfa sos1r eps8r csrc pi3kr pten ship2 pdk1 pp2a mtorr mkp pp2b; do

init="erbb1 1, erbb2 0, erbb4 1, $curinput 1"
echo "--- $init"
for z in $outputs; do
  echo "# $z 1"
  ./unitrun.sh $mode "x" --no-debug --initial-state "$init" -i $ph $z 1
  [ $? -eq 137 ] && echo '*** Killed ***'
done

done

echo -n "End time: " && date
(echo -n "End time: " && date) >&2

